import React, {useState} from "react";
import Head from "next/head";
import SignUpModal from "../components/SignUpModal";

export default function Home() {
  const [showModal, setModal] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Developer&apos;s Cult</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {showModal && <SignUpModal/> }
      
    </div>
  )
}
